import { createHash, randomBytes } from "node:crypto";
import { loadEnvConfig } from "@next/env";
import { expect, request as playwrightRequest, test, type APIRequestContext, type APIResponse } from "@playwright/test";
import { Client } from "pg";

loadEnvConfig(process.cwd());

const baseURL = process.env.E2E_BASE_URL ?? "http://127.0.0.1:8000";
const runId = `${Date.now()}_${randomBytes(3).toString("hex")}`;
const password = `CodexE2E!${runId}`;
const proofPng = Buffer.from(
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScLttAAAAABJRU5ErkJggg==",
  "base64",
);

type AppUser = { id: number; name: string; username: string; email: string; role: "admin" | "customer" };
type Event = { id: number; title: string; price: number; stock: number; isDemo: boolean };
type Order = { id: number; event: Event; quantity: number; total: number; status: string; proofName?: string };

const createdUsernames = new Set<string>();
const createdEventTitles = new Set<string>();
const contexts: APIRequestContext[] = [];

async function dbConnection(): Promise<Client> {
  const connectionString = process.env.DATABASE_URL;
  if (!connectionString) throw new Error("DATABASE_URL harus tersedia untuk pengujian E2E");
  const client = new Client({ connectionString });
  await client.connect();
  return client;
}

async function context(): Promise<APIRequestContext> {
  const api = await playwrightRequest.newContext({ baseURL });
  contexts.push(api);
  return api;
}

async function json<T>(response: APIResponse, status: number): Promise<T> {
  expect(response.status(), (await response.text()).slice(0, 500)).toBe(status);
  return response.json() as Promise<T>;
}

async function register(label: string): Promise<{ api: APIRequestContext; user: AppUser; credentials: { username: string; email: string; password: string } }> {
  const api = await context();
  const username = `codex_e2e_${runId}_${label}`;
  const email = `${username}@example.test`;
  createdUsernames.add(username);
  const result = await json<{ user: AppUser }>(await api.post("/api/auth/register", {
    data: { name: `Test ${label}`, username, email, password },
  }), 201);
  expect(result.user).toMatchObject({ username, email, role: "customer" });
  return { api, user: result.user, credentials: { username, email, password } };
}

async function adminContext(): Promise<APIRequestContext> {
  expect(process.env.ADMIN_EMAIL, "ADMIN_EMAIL harus tersedia di .env.local").toBeTruthy();
  expect(process.env.ADMIN_PASSWORD, "ADMIN_PASSWORD harus tersedia di .env.local").toBeTruthy();
  const api = await context();
  const result = await json<{ user: AppUser }>(await api.post("/api/auth/login", {
    data: { identifier: process.env.ADMIN_EMAIL, password: process.env.ADMIN_PASSWORD },
  }), 200);
  expect(result.user.role).toBe("admin");
  return api;
}

async function createEvent(api: APIRequestContext, label: string, stock = 5): Promise<Event> {
  const title = `codex_e2e_${runId}_${label} Live`;
  createdEventTitles.add(title);
  const result = await json<{ event: Event }>(await api.post("/api/events", {
    data: {
      title,
      startsAt: new Date(Date.now() + 120 * 24 * 60 * 60 * 1000).toISOString(),
      venue: "Test Arena",
      city: "Jakarta",
      description: "Konser sementara untuk pengujian API MelodyTix.",
      imageUrl: "/images/sheila.jpg",
      price: 125000,
      stock,
      featured: false,
      isDemo: true,
    },
  }), 201);
  expect(result.event).toMatchObject({ title, stock, price: 125000, isDemo: true });
  return result.event;
}

async function order(api: APIRequestContext, eventId: number, quantity: number): Promise<Order> {
  const result = await json<{ order: Order }>(await api.post("/api/orders", {
    multipart: {
      eventId: String(eventId),
      quantity: String(quantity),
      proof: { name: "codex-e2e-proof.png", mimeType: "image/png", buffer: proofPng },
    },
  }), 201);
  return result.order;
}

test.describe("MelodyTix API", () => {
  // The same API needs one run, even though UI tests run in desktop and mobile projects.
  test.beforeEach(async ({}, testInfo) => {
    test.skip(testInfo.project.name !== "desktop-chrome", "API contract runs once");
  });

  test.afterAll(async () => {
    await Promise.all(contexts.map((api) => api.dispose()));
    if (!createdUsernames.size && !createdEventTitles.size) return;

    // Match only names generated by this run. Never alter existing customer or admin records.
    const connection = await dbConnection();
    try {
      const userIds: number[] = [];
      const eventIds: number[] = [];
      for (const username of createdUsernames) {
        const { rows } = await connection.query<{ id: number }>(
          'SELECT id FROM "user" WHERE username=$1', [username],
        );
        userIds.push(...rows.map((row) => row.id));
      }
      for (const title of createdEventTitles) {
        const { rows } = await connection.query<{ id: number }>(
          "SELECT id FROM keranjang WHERE nama_konser=$1", [title],
        );
        eventIds.push(...rows.map((row) => row.id));
      }
      await connection.query("BEGIN");
      if (userIds.length || eventIds.length) {
        await connection.query(
          "DELETE FROM pesanan WHERE user_id = ANY($1::integer[]) OR event_id = ANY($2::integer[])",
          [userIds, eventIds],
        );
      }
      await connection.query("DELETE FROM keranjang WHERE id = ANY($1::integer[])", [eventIds]);
      await connection.query('DELETE FROM "user" WHERE id = ANY($1::integer[])', [userIds]);
      await connection.query("COMMIT");
    } catch (error) {
      await connection.query("ROLLBACK");
      throw error;
    } finally {
      await connection.end();
    }
  });

  test("public events and register, login, session, logout", async () => {
    const anonymous = await context();
    const before = await json<{ user: AppUser | null }>(await anonymous.get("/api/auth/me"), 200);
    expect(before.user).toBeNull();
    const events = await json<{ events: Event[] }>(await anonymous.get("/api/events"), 200);
    expect(Array.isArray(events.events)).toBe(true);
    expect((await anonymous.get("/api/events/not-an-id")).status()).toBe(400);

    const { api, user, credentials } = await register("auth");
    expect((await json<{ user: AppUser }>(await api.get("/api/auth/me"), 200)).user.id).toBe(user.id);
    expect((await api.post("/api/auth/register", {
      data: { name: "Duplicate User", ...credentials },
    })).status()).toBe(409);
    expect((await api.post("/api/auth/logout")).status()).toBe(200);
    expect((await json<{ user: null }>(await api.get("/api/auth/me"), 200)).user).toBeNull();
    expect((await api.post("/api/auth/login", {
      data: { identifier: credentials.email, password: "wrong-password" },
    })).status()).toBe(401);
    const login = await json<{ user: AppUser }>(await api.post("/api/auth/login", {
      data: { identifier: credentials.email, password: credentials.password },
    }), 200);
    expect(login.user.id).toBe(user.id);
    expect((await json<{ user: AppUser }>(await api.get("/api/auth/me"), 200)).user.id).toBe(user.id);
  });

  test("customer profile and password update", async () => {
    const { api, user, credentials } = await register("profile");
    const changedEmail = `changed_${credentials.email}`;
    const updated = await json<{ user: AppUser }>(await api.patch("/api/profile", {
      data: { name: "Nama Setelah Diubah", email: changedEmail },
    }), 200);
    expect(updated.user).toMatchObject({ id: user.id, name: "Nama Setelah Diubah", email: changedEmail });
    expect((await api.post("/api/profile/password", {
      data: { currentPassword: "wrong-password", newPassword: "Different!Password123" },
    })).status()).toBe(400);
    const newPassword = `New!${password}`;
    expect((await api.post("/api/profile/password", {
      data: { currentPassword: credentials.password, newPassword },
    })).status()).toBe(200);
    expect((await json<{ user: AppUser }>(await api.get("/api/auth/me"), 200)).user.id).toBe(user.id);
    await json<{ ok: boolean }>(await api.post("/api/auth/logout"), 200);
    expect((await api.post("/api/auth/login", {
      data: { identifier: changedEmail, password: credentials.password },
    })).status()).toBe(401);
    const login = await json<{ user: AppUser }>(await api.post("/api/auth/login", {
      data: { identifier: changedEmail, password: newPassword },
    }), 200);
    expect(login.user.id).toBe(user.id);
  });

  test("legacy MD5 account upgrades password hash after a successful login", async () => {
    const username = `codex_e2e_${runId}_legacy`;
    const email = `${username}@example.test`;
    createdUsernames.add(username);
    const legacyPassword = `Legacy!${runId}`;
    const md5 = createHash("md5").update(legacyPassword).digest("hex");
    const connection = await dbConnection();
    try {
      await connection.query(
        'INSERT INTO "user" (username,password,nama,email,level) VALUES ($1,$2,$3,$4,\'customer\')',
        [username, md5, "Legacy Test User", email],
      );
    } finally {
      await connection.end();
    }
    const api = await context();
    const login = await json<{ user: AppUser }>(await api.post("/api/auth/login", {
      data: { identifier: username, password: legacyPassword },
    }), 200);
    expect(login.user.username).toBe(username);
    const verify = await dbConnection();
    try {
      const { rows } = await verify.query<{ password: string }>(
        'SELECT password FROM "user" WHERE username=$1', [username],
      );
      expect(rows[0]?.password).toMatch(/^\$2[aby]\$/);
      expect(rows[0]?.password).not.toBe(md5);
    } finally {
      await verify.end();
    }
  });

  test("admin event CRUD and role boundaries", async () => {
    const anonymous = await context();
    const customer = await register("roles");
    expect((await anonymous.get("/api/admin/stats")).status()).toBe(401);
    expect((await customer.api.get("/api/admin/stats")).status()).toBe(403);
    expect((await customer.api.get("/api/admin/users")).status()).toBe(403);
    expect((await customer.api.post("/api/events", { data: {} })).status()).toBe(403);

    const admin = await adminContext();
    const created = await createEvent(admin, "crud");
    const detail = await json<{ event: Event }>(await anonymous.get(`/api/events/${created.id}`), 200);
    expect(detail.event.title).toBe(created.title);
    const listing = await json<{ events: Event[] }>(await anonymous.get("/api/events"), 200);
    expect(listing.events.some((event) => event.id === created.id)).toBe(true);
    expect((await admin.patch(`/api/events/${created.id}`, {
      headers: { origin: "https://cross-origin.example" }, data: { venue: "Other Hall" },
    })).status()).toBe(403);
    const updated = await json<{ event: Event & { venue: string } }>(await admin.patch(`/api/events/${created.id}`, {
      data: { venue: "Updated Arena", price: 150000, featured: true },
    }), 200);
    expect(updated.event).toMatchObject({ id: created.id, venue: "Updated Arena", price: 150000 });
    expect((await admin.patch(`/api/events/${created.id}`, { data: { stock: 6 } })).status()).toBe(400);
    const stockUpdated = await json<{ event: Event }>(await admin.patch(`/api/events/${created.id}`, {
      data: { stock: 6, expectedStock: created.stock },
    }), 200);
    expect(stockUpdated.event.stock).toBe(6);
    expect((await admin.patch(`/api/events/${created.id}`, {
      data: { stock: 7, expectedStock: created.stock },
    })).status()).toBe(409);
    const users = await json<{ users: AppUser[] }>(await admin.get("/api/admin/users"), 200);
    expect(users.users.some((item) => item.id === customer.user.id)).toBe(true);
    const adminMe = await json<{ user: AppUser }>(await admin.get("/api/auth/me"), 200);
    expect((await admin.patch(`/api/admin/users/${adminMe.user.id}`, {
      data: { role: "customer" },
    })).status()).toBe(400);
    const promoted = await json<{ user: AppUser }>(await admin.patch(`/api/admin/users/${customer.user.id}`, {
      data: { role: "admin" },
    }), 200);
    expect(promoted.user.role).toBe("admin");
    expect((await customer.api.get("/api/admin/stats")).status()).toBe(200);
    const demoted = await json<{ user: AppUser }>(await admin.patch(`/api/admin/users/${customer.user.id}`, {
      data: { role: "customer" },
    }), 200);
    expect(demoted.user.role).toBe("customer");
    expect((await customer.api.get("/api/admin/stats")).status()).toBe(403);
    await json<{ ok: boolean }>(await admin.delete(`/api/events/${created.id}`), 200);
    expect((await anonymous.get(`/api/events/${created.id}`)).status()).toBe(404);
    const after = await json<{ events: Event[] }>(await anonymous.get("/api/events"), 200);
    expect(after.events.some((event) => event.id === created.id)).toBe(false);
  });

  test("ticket purchase, private proof, admin approval and rejection", async () => {
    const admin = await adminContext();
    const concert = await createEvent(admin, "orders", 4);
    const buyer = await register("buyer");
    const other = await register("other");
    const anonymous = await context();

    expect((await anonymous.get("/api/orders")).status()).toBe(401);
    expect((await anonymous.post("/api/orders", { multipart: { eventId: String(concert.id), quantity: "1" } })).status()).toBe(401);
    expect((await buyer.api.post("/api/orders", {
      multipart: { eventId: String(concert.id), quantity: "1", proof: "not an image" },
    })).status()).toBe(400);
    expect((await buyer.api.post("/api/orders", {
      multipart: {
        eventId: String(concert.id), quantity: "0",
        proof: { name: "proof.png", mimeType: "image/png", buffer: proofPng },
      },
    })).status()).toBe(400);

    const first = await order(buyer.api, concert.id, 2);
    const second = await order(other.api, concert.id, 2);
    expect(first).toMatchObject({ quantity: 2, total: 250000, status: "pending", proofName: "codex-e2e-proof.png" });
    expect(second.status).toBe("pending");
    expect((await json<{ event: Event }>(await anonymous.get(`/api/events/${concert.id}`), 200)).event.stock).toBe(0);
    expect((await buyer.api.post("/api/orders", {
      multipart: {
        eventId: String(concert.id), quantity: "1",
        proof: { name: "proof.png", mimeType: "image/png", buffer: proofPng },
      },
    })).status()).toBe(409);

    const ownOrders = await json<{ orders: Order[] }>(await buyer.api.get("/api/orders"), 200);
    expect(ownOrders.orders.some((item) => item.id === first.id)).toBe(true);
    expect(ownOrders.orders.some((item) => item.id === second.id)).toBe(false);
    expect((await json<{ order: Order }>(await buyer.api.get(`/api/orders/${first.id}`), 200)).order.id).toBe(first.id);
    expect((await other.api.get(`/api/orders/${first.id}`)).status()).toBe(403);
    expect((await other.api.get(`/api/orders/${first.id}/proof`)).status()).toBe(403);
    expect((await anonymous.get(`/api/orders/${first.id}/proof`)).status()).toBe(401);
    const proof = await buyer.api.get(`/api/orders/${first.id}/proof`);
    expect(proof.status()).toBe(200);
    expect(proof.headers()["content-type"]).toContain("image/png");
    expect(await proof.body()).toEqual(proofPng);
    expect((await admin.get(`/api/orders/${first.id}/proof`)).status()).toBe(200);

    const adminOrders = await json<{ orders: Order[] }>(await admin.get("/api/admin/orders"), 200);
    expect(adminOrders.orders.some((item) => item.id === first.id)).toBe(true);
    const approved = await json<{ order: Order }>(await admin.patch(`/api/admin/orders/${first.id}`, {
      data: { status: "approved" },
    }), 200);
    expect(approved.order.status).toBe("approved");
    const rejected = await json<{ order: Order }>(await admin.patch(`/api/admin/orders/${second.id}`, {
      data: { status: "rejected" },
    }), 200);
    expect(rejected.order.status).toBe("rejected");
    expect((await admin.patch(`/api/admin/orders/${second.id}`, {
      data: { status: "rejected" },
    })).status()).toBe(409);
    expect((await json<{ event: Event }>(await anonymous.get(`/api/events/${concert.id}`), 200)).event.stock).toBe(2);
    const stats = await json<{ stats: { orders: number; approved: number; rejected: number } }>(
      await admin.get("/api/admin/stats"), 200,
    );
    expect(stats.stats.orders).toBeGreaterThanOrEqual(2);
    expect(stats.stats.approved).toBeGreaterThanOrEqual(1);
    expect(stats.stats.rejected).toBeGreaterThanOrEqual(1);

    // Legacy rows may retain a username after losing the stable user link.
    // The name alone must never grant access to an order or its proof.
    const connection = await dbConnection();
    try {
      await connection.query("UPDATE pesanan SET user_id=NULL WHERE idpesanan=$1", [first.id]);
    } finally {
      await connection.end();
    }
    const afterOrphaning = await json<{ orders: Order[] }>(await buyer.api.get("/api/orders"), 200);
    expect(afterOrphaning.orders.some((item) => item.id === first.id)).toBe(false);
    expect((await buyer.api.get(`/api/orders/${first.id}`)).status()).toBe(403);
    expect((await buyer.api.get(`/api/orders/${first.id}/proof`)).status()).toBe(403);
    expect((await admin.get(`/api/orders/${first.id}`)).status()).toBe(200);
  });
});
