-- PostgreSQL bootstrap schema for MelodyTix. The additive changes in
-- modern.sql keep migration repeatable for a database with these base tables.

CREATE TABLE IF NOT EXISTS "user" (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  nama VARCHAR(150) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  level VARCHAR(20) NOT NULL DEFAULT 'customer'
);

CREATE TABLE IF NOT EXISTS keranjang (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama_konser VARCHAR(255) NOT NULL,
  waktu TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  gambar VARCHAR(255) NOT NULL,
  harga NUMERIC(15, 2) NOT NULL,
  stok_tiket INTEGER NOT NULL,
  deskripsi TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS pesanan (
  idpesanan INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(100) NOT NULL,
  nama_konser VARCHAR(255) NOT NULL,
  quantity INTEGER NOT NULL,
  tanggal_pembelian TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Bangkok'),
  total_harga NUMERIC(15, 2) NOT NULL,
  buktitf BYTEA NOT NULL,
  tipe_file VARCHAR(100) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'pending'
);

CREATE INDEX IF NOT EXISTS idx_pesanan_username ON pesanan (username);
